# Configuration file for thmEnchantments
# Coded with <3 by thmihnea

actions:
  task-timer: 20 # How often should runnable actions be run. Set in ticks (20 ticks = 1 second, roughly).
  three-shot-particle: "VILLAGER_HAPPY"
  # For a list of available particles, access this link: https://gyazo.com/270c38b8382590d5baa2543ee8180fa0

enchants: # Reffer to the layout down below.
  earthquake:
    id: 100
    name: "Earthquake"
    startLevel: 1
    maxLevel: 1
    enchantmentTarget: "WEAPON"
    actions:
      - "earthquake"
  stattrak:
    id: 101
    name: "Stat Trak"
    startLevel: 1
    maxLevel: 1
    enchantmentTarget: "WEAPON"
    actions:
      - "statTrak(player)"
  blaster:
    id: 102
    name: "Blaster"
    startLevel: 1
    maxLevel: 1
    enchantmentTarget: "BOW"
    actions:
      - "tripleShot"
  wings:
    id: 103
    name: "Wings"
    startLevel: 1
    maxLevel: 1
    enchantmentTarget: "ARMOR"
    actions:
      - "fullSetFly"
  allInOne:
    id: 104
    name: "All in One"
    startLevel: 1
    maxLevel: 1
    enchantmentTarget: "WEAPON"
    actions:
      - "tripleShot"
      - "statTrak(player)"
      - "earthquake"